Fix lifetimes for entrypoint::ProcessInstruction
Without explicit lifetime annotations, the type desugars to

    for<'r, 's, 't0, 't1> fn(&'r Pubkey, &'s [AccountInfo<'t0>], &'t1 [u8]) -> Result<_, _>

Note that 's and 't0 are not related here. This is not what you want in
practice, because you put AccountInfos that hold 't0 pointer inside a
slice of lifetime 's, you want 't0 to outlive 's; this is the only way
that you can call such a function in practice.

But because ProcessInstruction is used in argument position, that has
worked out until now. If you pass in a function that can deal with more
general lifetimes, you can always call it with more constrained ones.
But if you need the more constrained lifetimes because it's the only
way to implement your `process_instruction`, then you can no longer pass
that `process_instruction` to the `processor!` macro, because it expects
a more general function. That then leads to an error like this one:

    error[E0308]: mismatched types
      --> (...)
       |
    13 |     ...(processor!(processor::Processor::process));
       |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ one type is more general than the other
       |
       = note: expected fn pointer `for<'r, 's, 't0, 't1> fn(&'r Pubkey, &'s [AccountInfo<'t0>], &'t1 [u8]) -> Result<_, _>`
                  found fn pointer `for<'a> fn(&'a Pubkey, &'a [AccountInfo<'a>], &'a [u8]) -> Result<_, _>`

The simplest solution is to use a single lifetime for all arguments,
notably the slice and the AccountInfo.